// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireLease = `-- name: AcquireLease :one
INSERT INTO leases (id, job_id, attempt_id, worker_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, attempt_id, worker_id, acquired_at, expires_at, released_at
`

type AcquireLeaseParams struct {
	ID        uuid.UUID
	JobID     uuid.UUID
	AttemptID uuid.UUID
	WorkerID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (Lease, error) {
	row := q.db.QueryRow(ctx, acquireLease,
		arg.ID,
		arg.JobID,
		arg.AttemptID,
		arg.WorkerID,
		arg.ExpiresAt,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.WorkerID,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const appendLogChunk = `-- name: AppendLogChunk :one
INSERT INTO log_chunks (job_id, attempt_id, seq, stream, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, attempt_id, seq, stream, data, created_at
`

type AppendLogChunkParams struct {
	JobID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int32
	Stream    string
	Data      []byte
}

func (q *Queries) AppendLogChunk(ctx context.Context, arg AppendLogChunkParams) (LogChunk, error) {
	row := q.db.QueryRow(ctx, appendLogChunk,
		arg.JobID,
		arg.AttemptID,
		arg.Seq,
		arg.Stream,
		arg.Data,
	)
	var i LogChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.Seq,
		&i.Stream,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO job_attempts (id, job_id, attempt_number, worker_id)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at
`

type CreateAttemptParams struct {
	ID            uuid.UUID
	JobID         uuid.UUID
	AttemptNumber int32
	WorkerID      uuid.UUID
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.JobID,
		arg.AttemptNumber,
		arg.WorkerID,
	)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Status,
		&i.ExitCode,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listAttempts = `-- name: ListAttempts :many
SELECT id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListAttempts(ctx context.Context, jobID uuid.UUID) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobAttempt{}
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.WorkerID,
			&i.Status,
			&i.ExitCode,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogChunks = `-- name: ListLogChunks :many
SELECT id, job_id, attempt_id, seq, stream, data, created_at FROM log_chunks
WHERE job_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListLogChunksParams struct {
	JobID    uuid.UUID
	AfterID  int64
	RowLimit int32
}

func (q *Queries) ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]LogChunk, error) {
	rows, err := q.db.Query(ctx, listLogChunks, arg.JobID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogChunk{}
	for rows.Next() {
		var i LogChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Seq,
			&i.Stream,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
