// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const acquireLease = `-- name: AcquireLease :one
INSERT INTO leases (id, job_id, attempt_id, worker_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, attempt_id, worker_id, acquired_at, expires_at, released_at
`

type AcquireLeaseParams struct {
	ID        uuid.UUID
	JobID     uuid.UUID
	AttemptID uuid.UUID
	WorkerID  uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (Lease, error) {
	row := q.db.QueryRow(ctx, acquireLease,
		arg.ID,
		arg.JobID,
		arg.AttemptID,
		arg.WorkerID,
		arg.ExpiresAt,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.WorkerID,
		&i.AcquiredAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
	)
	return i, err
}

const appendLogChunk = `-- name: AppendLogChunk :one
INSERT INTO log_chunks (job_id, attempt_id, seq, stream, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, attempt_id, seq, stream, data, created_at
`

type AppendLogChunkParams struct {
	JobID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int32
	Stream    string
	Data      []byte
}

func (q *Queries) AppendLogChunk(ctx context.Context, arg AppendLogChunkParams) (LogChunk, error) {
	row := q.db.QueryRow(ctx, appendLogChunk,
		arg.JobID,
		arg.AttemptID,
		arg.Seq,
		arg.Stream,
		arg.Data,
	)
	var i LogChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.Seq,
		&i.Stream,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const attemptLogBytes = `-- name: AttemptLogBytes :one
SELECT coalesce(sum(octet_length(data)), 0)::bigint AS total
FROM log_chunks
WHERE attempt_id = $1
`

func (q *Queries) AttemptLogBytes(ctx context.Context, attemptID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, attemptLogBytes, attemptID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createArtifact = `-- name: CreateArtifact :execrows
INSERT INTO artifacts (id, job_id, attempt_id, name, content_type, storage_key, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
`

type CreateArtifactParams struct {
	ID          uuid.UUID
	JobID       uuid.UUID
	AttemptID   *uuid.UUID
	Name        string
	ContentType string
	StorageKey  string
	SizeBytes   int64
	Sha256      string
}

// CreateArtifact ignores a second row for the same job, attempt, and name.
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, createArtifact,
		arg.ID,
		arg.JobID,
		arg.AttemptID,
		arg.Name,
		arg.ContentType,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Sha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO job_attempts (id, job_id, attempt_number, worker_id)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at
`

type CreateAttemptParams struct {
	ID            uuid.UUID
	JobID         uuid.UUID
	AttemptNumber int32
	WorkerID      uuid.UUID
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.JobID,
		arg.AttemptNumber,
		arg.WorkerID,
	)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Status,
		&i.ExitCode,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createFailure = `-- name: CreateFailure :exec
INSERT INTO failures (id, job_id, attempt_id, category, message, details)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateFailureParams struct {
	ID        uuid.UUID
	JobID     uuid.UUID
	AttemptID *uuid.UUID
	Category  string
	Message   string
	Details   json.RawMessage
}

func (q *Queries) CreateFailure(ctx context.Context, arg CreateFailureParams) error {
	_, err := q.db.Exec(ctx, createFailure,
		arg.ID,
		arg.JobID,
		arg.AttemptID,
		arg.Category,
		arg.Message,
		arg.Details,
	)
	return err
}

const createRuntime = `-- name: CreateRuntime :one
INSERT INTO runtimes (
    id, attempt_id, kind, role, image, container_id, volume_name,
    cpu_millis, memory_mb, network_enabled, created_at, destroyed_at
) VALUES (
    $1, $2, 'docker', $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, attempt_id, kind, role, image, container_id, volume_name, cpu_millis, memory_mb, network_enabled, created_at, destroyed_at
`

type CreateRuntimeParams struct {
	ID             uuid.UUID
	AttemptID      uuid.UUID
	Role           string
	Image          string
	ContainerID    *string
	VolumeName     *string
	CpuMillis      int32
	MemoryMB       int32
	NetworkEnabled bool
	CreatedAt      time.Time
	DestroyedAt    *time.Time
}

func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime,
		arg.ID,
		arg.AttemptID,
		arg.Role,
		arg.Image,
		arg.ContainerID,
		arg.VolumeName,
		arg.CpuMillis,
		arg.MemoryMB,
		arg.NetworkEnabled,
		arg.CreatedAt,
		arg.DestroyedAt,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.Kind,
		&i.Role,
		&i.Image,
		&i.ContainerID,
		&i.VolumeName,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.NetworkEnabled,
		&i.CreatedAt,
		&i.DestroyedAt,
	)
	return i, err
}

const createVerificationCheck = `-- name: CreateVerificationCheck :exec
INSERT INTO verification_checks (
    id, verification_run_id, name, kind, command, status, exit_code, output, started_at, finished_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
`

type CreateVerificationCheckParams struct {
	ID                uuid.UUID
	VerificationRunID uuid.UUID
	Name              string
	Kind              string
	Command           *string
	Status            string
	ExitCode          *int32
	Output            string
	StartedAt         *time.Time
	FinishedAt        *time.Time
}

func (q *Queries) CreateVerificationCheck(ctx context.Context, arg CreateVerificationCheckParams) error {
	_, err := q.db.Exec(ctx, createVerificationCheck,
		arg.ID,
		arg.VerificationRunID,
		arg.Name,
		arg.Kind,
		arg.Command,
		arg.Status,
		arg.ExitCode,
		arg.Output,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const createVerificationRun = `-- name: CreateVerificationRun :one
INSERT INTO verification_runs (id, job_id, attempt_id, status, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, attempt_id, status, started_at, finished_at
`

type CreateVerificationRunParams struct {
	ID         uuid.UUID
	JobID      uuid.UUID
	AttemptID  uuid.UUID
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
}

func (q *Queries) CreateVerificationRun(ctx context.Context, arg CreateVerificationRunParams) (VerificationRun, error) {
	row := q.db.QueryRow(ctx, createVerificationRun,
		arg.ID,
		arg.JobID,
		arg.AttemptID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishAttempt = `-- name: FinishAttempt :one
UPDATE job_attempts
SET status      = $1,
    error       = $2,
    finished_at = now()
WHERE id = $3 AND status = 'RUNNING'
RETURNING id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at
`

type FinishAttemptParams struct {
	Status string
	Error  *string
	ID     uuid.UUID
}

// FinishAttempt ends a RUNNING attempt; it returns no row if the attempt has
// already finished.
func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, finishAttempt, arg.Status, arg.Error, arg.ID)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Status,
		&i.ExitCode,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, job_id, attempt_id, name, content_type, storage_key, size_bytes, sha256, created_at FROM artifacts
WHERE id = $1 AND job_id = $2
`

type GetArtifactParams struct {
	ID    uuid.UUID
	JobID uuid.UUID
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.ID, arg.JobID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptID,
		&i.Name,
		&i.ContentType,
		&i.StorageKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertLogChunk = `-- name: InsertLogChunk :execrows
INSERT INTO log_chunks (job_id, attempt_id, seq, stream, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (attempt_id, seq) DO NOTHING
`

type InsertLogChunkParams struct {
	JobID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int32
	Stream    string
	Data      []byte
}

// InsertLogChunk stores one chunk; a chunk re-sent with the same seq is ignored.
func (q *Queries) InsertLogChunk(ctx context.Context, arg InsertLogChunkParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLogChunk,
		arg.JobID,
		arg.AttemptID,
		arg.Seq,
		arg.Stream,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, job_id, attempt_id, name, content_type, storage_key, size_bytes, sha256, created_at FROM artifacts
WHERE job_id = $1
ORDER BY created_at, name
`

func (q *Queries) ListArtifacts(ctx context.Context, jobID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Name,
			&i.ContentType,
			&i.StorageKey,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptLogChunks = `-- name: ListAttemptLogChunks :many
SELECT id, job_id, attempt_id, seq, stream, data, created_at FROM log_chunks
WHERE attempt_id = $1
ORDER BY seq
`

func (q *Queries) ListAttemptLogChunks(ctx context.Context, attemptID uuid.UUID) ([]LogChunk, error) {
	rows, err := q.db.Query(ctx, listAttemptLogChunks, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogChunk{}
	for rows.Next() {
		var i LogChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Seq,
			&i.Stream,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttempts = `-- name: ListAttempts :many
SELECT id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at FROM job_attempts
WHERE job_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListAttempts(ctx context.Context, jobID uuid.UUID) ([]JobAttempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobAttempt{}
	for rows.Next() {
		var i JobAttempt
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptNumber,
			&i.WorkerID,
			&i.Status,
			&i.ExitCode,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCancelRequestedAttempts = `-- name: ListCancelRequestedAttempts :many
SELECT a.id FROM job_attempts a
JOIN jobs j ON j.id = a.job_id
WHERE a.worker_id = $1
  AND a.status = 'RUNNING'
  AND j.cancel_requested_at IS NOT NULL
ORDER BY a.started_at
`

// ListCancelRequestedAttempts returns a worker's running attempts whose job
// has a pending cancellation request.
func (q *Queries) ListCancelRequestedAttempts(ctx context.Context, workerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCancelRequestedAttempts, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailures = `-- name: ListFailures :many
SELECT id, job_id, attempt_id, category, message, details, created_at FROM failures
WHERE job_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListFailures(ctx context.Context, jobID uuid.UUID) ([]Failure, error) {
	rows, err := q.db.Query(ctx, listFailures, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Failure{}
	for rows.Next() {
		var i Failure
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Category,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogChunks = `-- name: ListLogChunks :many
SELECT id, job_id, attempt_id, seq, stream, data, created_at FROM log_chunks
WHERE job_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListLogChunksParams struct {
	JobID    uuid.UUID
	AfterID  int64
	RowLimit int32
}

func (q *Queries) ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]LogChunk, error) {
	rows, err := q.db.Query(ctx, listLogChunks, arg.JobID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogChunk{}
	for rows.Next() {
		var i LogChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Seq,
			&i.Stream,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT r.id, r.attempt_id, r.kind, r.role, r.image, r.container_id, r.volume_name, r.cpu_millis, r.memory_mb, r.network_enabled, r.created_at, r.destroyed_at FROM runtimes r
JOIN job_attempts a ON a.id = r.attempt_id
WHERE a.job_id = $1
ORDER BY r.created_at, r.id
`

func (q *Queries) ListRuntimes(ctx context.Context, jobID uuid.UUID) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listRuntimes, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.Kind,
			&i.Role,
			&i.Image,
			&i.ContainerID,
			&i.VolumeName,
			&i.CpuMillis,
			&i.MemoryMB,
			&i.NetworkEnabled,
			&i.CreatedAt,
			&i.DestroyedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationChecks = `-- name: ListVerificationChecks :many
SELECT c.id, c.verification_run_id, c.name, c.kind, c.command, c.status, c.exit_code, c.output, c.started_at, c.finished_at FROM verification_checks c
JOIN verification_runs r ON r.id = c.verification_run_id
WHERE r.job_id = $1
ORDER BY c.verification_run_id, c.id
`

func (q *Queries) ListVerificationChecks(ctx context.Context, jobID uuid.UUID) ([]VerificationCheck, error) {
	rows, err := q.db.Query(ctx, listVerificationChecks, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationCheck{}
	for rows.Next() {
		var i VerificationCheck
		if err := rows.Scan(
			&i.ID,
			&i.VerificationRunID,
			&i.Name,
			&i.Kind,
			&i.Command,
			&i.Status,
			&i.ExitCode,
			&i.Output,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationRuns = `-- name: ListVerificationRuns :many
SELECT id, job_id, attempt_id, status, started_at, finished_at FROM verification_runs
WHERE job_id = $1
ORDER BY started_at, id
`

func (q *Queries) ListVerificationRuns(ctx context.Context, jobID uuid.UUID) ([]VerificationRun, error) {
	rows, err := q.db.Query(ctx, listVerificationRuns, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerificationRun{}
	for rows.Next() {
		var i VerificationRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AttemptID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttempt = `-- name: LockAttempt :one
SELECT id, job_id, attempt_number, worker_id, status, exit_code, error, started_at, finished_at FROM job_attempts
WHERE id = $1
FOR UPDATE
`

// LockAttempt serializes reports about one attempt for the rest of the transaction.
func (q *Queries) LockAttempt(ctx context.Context, id uuid.UUID) (JobAttempt, error) {
	row := q.db.QueryRow(ctx, lockAttempt, id)
	var i JobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.Status,
		&i.ExitCode,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const nextAttemptNumber = `-- name: NextAttemptNumber :one
SELECT (coalesce(max(attempt_number), 0) + 1)::integer AS next
FROM job_attempts
WHERE job_id = $1
`

func (q *Queries) NextAttemptNumber(ctx context.Context, jobID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttemptNumber, jobID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const recordAttemptExit = `-- name: RecordAttemptExit :exec
UPDATE job_attempts
SET exit_code = $1
WHERE id = $2
`

type RecordAttemptExitParams struct {
	ExitCode *int32
	ID       uuid.UUID
}

func (q *Queries) RecordAttemptExit(ctx context.Context, arg RecordAttemptExitParams) error {
	_, err := q.db.Exec(ctx, recordAttemptExit, arg.ExitCode, arg.ID)
	return err
}
