// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countJobsByState = `-- name: CountJobsByState :many
SELECT state, count(*) AS count
FROM jobs
GROUP BY state
ORDER BY state
`

type CountJobsByStateRow struct {
	State string
	Count int64
}

func (q *Queries) CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error) {
	rows, err := q.db.Query(ctx, countJobsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStateRow{}
	for rows.Next() {
		var i CountJobsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, workload_id, scheduled_at)
VALUES ($1, $2, $3)
RETURNING id, number, workload_id, state, assigned_worker_id, scheduled_at, cancel_requested_at, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	ID          uuid.UUID
	WorkloadID  uuid.UUID
	ScheduledAt *time.Time
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ID, arg.WorkloadID, arg.ScheduledAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WorkloadID,
		&i.State,
		&i.AssignedWorkerID,
		&i.ScheduledAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createWorkload = `-- name: CreateWorkload :one
INSERT INTO workloads (
    id, idempotency_key, repository_url, revision, command, image, verification_command,
    acceptance_criteria, cpu_millis, memory_mb, timeout_seconds, network_enabled, spec
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13
)
RETURNING id, idempotency_key, repository_url, revision, command, image, verification_command, acceptance_criteria, cpu_millis, memory_mb, timeout_seconds, network_enabled, spec, created_at
`

type CreateWorkloadParams struct {
	ID                  uuid.UUID
	IdempotencyKey      *string
	RepositoryURL       string
	Revision            string
	Command             string
	Image               string
	VerificationCommand *string
	AcceptanceCriteria  []string
	CpuMillis           int32
	MemoryMB            int32
	TimeoutSeconds      int32
	NetworkEnabled      bool
	Spec                json.RawMessage
}

func (q *Queries) CreateWorkload(ctx context.Context, arg CreateWorkloadParams) (Workload, error) {
	row := q.db.QueryRow(ctx, createWorkload,
		arg.ID,
		arg.IdempotencyKey,
		arg.RepositoryURL,
		arg.Revision,
		arg.Command,
		arg.Image,
		arg.VerificationCommand,
		arg.AcceptanceCriteria,
		arg.CpuMillis,
		arg.MemoryMB,
		arg.TimeoutSeconds,
		arg.NetworkEnabled,
		arg.Spec,
	)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.RepositoryURL,
		&i.Revision,
		&i.Command,
		&i.Image,
		&i.VerificationCommand,
		&i.AcceptanceCriteria,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.TimeoutSeconds,
		&i.NetworkEnabled,
		&i.Spec,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, number, workload_id, state, assigned_worker_id, scheduled_at, cancel_requested_at, created_at, updated_at, started_at, finished_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WorkloadID,
		&i.State,
		&i.AssignedWorkerID,
		&i.ScheduledAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listTransitions = `-- name: ListTransitions :many
SELECT id, job_id, from_state, to_state, actor, reason, created_at FROM state_transitions
WHERE job_id = $1
ORDER BY id
`

func (q *Queries) ListTransitions(ctx context.Context, jobID uuid.UUID) ([]StateTransition, error) {
	rows, err := q.db.Query(ctx, listTransitions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StateTransition{}
	for rows.Next() {
		var i StateTransition
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.FromState,
			&i.ToState,
			&i.Actor,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransition = `-- name: RecordTransition :one
INSERT INTO state_transitions (job_id, from_state, to_state, actor, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, job_id, from_state, to_state, actor, reason, created_at
`

type RecordTransitionParams struct {
	JobID     uuid.UUID
	FromState *string
	ToState   string
	Actor     string
	Reason    string
}

func (q *Queries) RecordTransition(ctx context.Context, arg RecordTransitionParams) (StateTransition, error) {
	row := q.db.QueryRow(ctx, recordTransition,
		arg.JobID,
		arg.FromState,
		arg.ToState,
		arg.Actor,
		arg.Reason,
	)
	var i StateTransition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromState,
		&i.ToState,
		&i.Actor,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const transitionJob = `-- name: TransitionJob :one
UPDATE jobs
SET state = $1, updated_at = now()
WHERE id = $2 AND state = $3
RETURNING id, number, workload_id, state, assigned_worker_id, scheduled_at, cancel_requested_at, created_at, updated_at, started_at, finished_at
`

type TransitionJobParams struct {
	ToState   string
	ID        uuid.UUID
	FromState string
}

// TransitionJob is a compare-and-set: it returns no row when the job is no
// longer in from_state, so concurrent transitions cannot both succeed.
func (q *Queries) TransitionJob(ctx context.Context, arg TransitionJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, transitionJob, arg.ToState, arg.ID, arg.FromState)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WorkloadID,
		&i.State,
		&i.AssignedWorkerID,
		&i.ScheduledAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
