// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Artifact struct {
	ID          uuid.UUID
	JobID       uuid.UUID
	AttemptID   *uuid.UUID
	Name        string
	ContentType string
	StorageKey  string
	SizeBytes   int64
	Sha256      string
	CreatedAt   time.Time
}

type Delivery struct {
	ID             uuid.UUID
	JobID          uuid.UUID
	Kind           string
	Status         string
	IdempotencyKey string
	Target         string
	ExternalRef    *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Failure struct {
	ID        uuid.UUID
	JobID     uuid.UUID
	AttemptID *uuid.UUID
	Category  string
	Message   string
	Details   json.RawMessage
	CreatedAt time.Time
}

type Job struct {
	ID                uuid.UUID
	Number            int64
	WorkloadID        uuid.UUID
	State             string
	AssignedWorkerID  *uuid.UUID
	ScheduledAt       *time.Time
	CancelRequestedAt *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	StartedAt         *time.Time
	FinishedAt        *time.Time
}

type JobAttempt struct {
	ID            uuid.UUID
	JobID         uuid.UUID
	AttemptNumber int32
	WorkerID      uuid.UUID
	Status        string
	ExitCode      *int32
	Error         *string
	StartedAt     time.Time
	FinishedAt    *time.Time
}

type JobEvent struct {
	ID        int64
	JobID     uuid.UUID
	AttemptID *uuid.UUID
	Type      string
	Payload   json.RawMessage
	CreatedAt time.Time
}

type Lease struct {
	ID         uuid.UUID
	JobID      uuid.UUID
	AttemptID  uuid.UUID
	WorkerID   uuid.UUID
	AcquiredAt time.Time
	ExpiresAt  time.Time
	ReleasedAt *time.Time
}

type LogChunk struct {
	ID        int64
	JobID     uuid.UUID
	AttemptID uuid.UUID
	Seq       int32
	Stream    string
	Data      []byte
	CreatedAt time.Time
}

type Runtime struct {
	ID             uuid.UUID
	AttemptID      uuid.UUID
	Kind           string
	Role           string
	Image          string
	ContainerID    *string
	VolumeName     *string
	CpuMillis      int32
	MemoryMB       int32
	NetworkEnabled bool
	CreatedAt      time.Time
	DestroyedAt    *time.Time
}

type StateTransition struct {
	ID        int64
	JobID     uuid.UUID
	FromState *string
	ToState   string
	Actor     string
	Reason    string
	CreatedAt time.Time
}

type VerificationCheck struct {
	ID                uuid.UUID
	VerificationRunID uuid.UUID
	Name              string
	Kind              string
	Command           *string
	Status            string
	ExitCode          *int32
	Output            string
	StartedAt         *time.Time
	FinishedAt        *time.Time
}

type VerificationRun struct {
	ID         uuid.UUID
	JobID      uuid.UUID
	AttemptID  uuid.UUID
	Status     string
	StartedAt  time.Time
	FinishedAt *time.Time
}

type Worker struct {
	ID              uuid.UUID
	Name            string
	Slots           int32
	CpuMillis       int32
	MemoryMB        int32
	Metadata        json.RawMessage
	RegisteredAt    time.Time
	LastHeartbeatAt time.Time
	CpuUsedPercent  *float64
	MemoryUsedMB    *int32
}

type Workload struct {
	ID                  uuid.UUID
	IdempotencyKey      *string
	RepositoryURL       string
	Revision            string
	Command             string
	Image               string
	VerificationCommand *string
	AcceptanceCriteria  []string
	CpuMillis           int32
	MemoryMB            int32
	TimeoutSeconds      int32
	NetworkEnabled      bool
	Spec                json.RawMessage
	CreatedAt           time.Time
}
