// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (id, name, slots, cpu_millis, memory_mb, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slots, cpu_millis, memory_mb, metadata, registered_at, last_heartbeat_at, cpu_used_percent, memory_used_mb
`

type CreateWorkerParams struct {
	ID        uuid.UUID
	Name      string
	Slots     int32
	CpuMillis int32
	MemoryMB  int32
	Metadata  json.RawMessage
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.ID,
		arg.Name,
		arg.Slots,
		arg.CpuMillis,
		arg.MemoryMB,
		arg.Metadata,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
		&i.CpuUsedPercent,
		&i.MemoryUsedMB,
	)
	return i, err
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT id, name, slots, cpu_millis, memory_mb, metadata, registered_at, last_heartbeat_at, cpu_used_percent, memory_used_mb FROM workers
WHERE name = $1
`

func (q *Queries) GetWorkerByName(ctx context.Context, name string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
		&i.CpuUsedPercent,
		&i.MemoryUsedMB,
	)
	return i, err
}

const listSchedulableWorkers = `-- name: ListSchedulableWorkers :many
SELECT w.id, w.name, w.slots, count(j.id)::integer AS active_jobs
FROM workers w
LEFT JOIN jobs j
    ON j.assigned_worker_id = w.id
   AND j.state IN ('SCHEDULED', 'PREPARING', 'EXECUTING', 'VERIFYING')
WHERE w.last_heartbeat_at >= now() - make_interval(secs => $1::double precision)
GROUP BY w.id
ORDER BY w.registered_at, w.id
`

type ListSchedulableWorkersRow struct {
	ID         uuid.UUID
	Name       string
	Slots      int32
	ActiveJobs int32
}

// ListSchedulableWorkers returns online workers, oldest registration first,
// with the number of jobs they hold that have not finished. Liveness uses the
// database clock, the same clock that stamped last_heartbeat_at.
func (q *Queries) ListSchedulableWorkers(ctx context.Context, staleAfterSeconds float64) ([]ListSchedulableWorkersRow, error) {
	rows, err := q.db.Query(ctx, listSchedulableWorkers, staleAfterSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulableWorkersRow{}
	for rows.Next() {
		var i ListSchedulableWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slots,
			&i.ActiveJobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many
SELECT workers.id, workers.name, workers.slots, workers.cpu_millis, workers.memory_mb, workers.metadata, workers.registered_at, workers.last_heartbeat_at, workers.cpu_used_percent, workers.memory_used_mb, now()::timestamptz AS db_now
FROM workers
ORDER BY name
`

type ListWorkersRow struct {
	Worker Worker
	DBNow  time.Time
}

// ListWorkers also returns the database clock so liveness is judged against
// the same clock that stamped last_heartbeat_at.
func (q *Queries) ListWorkers(ctx context.Context) ([]ListWorkersRow, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkersRow{}
	for rows.Next() {
		var i ListWorkersRow
		if err := rows.Scan(
			&i.Worker.ID,
			&i.Worker.Name,
			&i.Worker.Slots,
			&i.Worker.CpuMillis,
			&i.Worker.MemoryMB,
			&i.Worker.Metadata,
			&i.Worker.RegisteredAt,
			&i.Worker.LastHeartbeatAt,
			&i.Worker.CpuUsedPercent,
			&i.Worker.MemoryUsedMB,
			&i.DBNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHeartbeat = `-- name: RecordHeartbeat :execrows
UPDATE workers
SET last_heartbeat_at = now(),
    cpu_used_percent  = $1,
    memory_used_mb    = $2
WHERE id = $3
`

type RecordHeartbeatParams struct {
	CpuUsedPercent *float64
	MemoryUsedMB   *int32
	ID             uuid.UUID
}

func (q *Queries) RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordHeartbeat, arg.CpuUsedPercent, arg.MemoryUsedMB, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorker = `-- name: UpsertWorker :one
INSERT INTO workers (id, name, slots, cpu_millis, memory_mb, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO UPDATE SET
    slots             = EXCLUDED.slots,
    cpu_millis        = EXCLUDED.cpu_millis,
    memory_mb         = EXCLUDED.memory_mb,
    metadata          = EXCLUDED.metadata,
    last_heartbeat_at = now()
RETURNING id, name, slots, cpu_millis, memory_mb, metadata, registered_at, last_heartbeat_at, cpu_used_percent, memory_used_mb
`

type UpsertWorkerParams struct {
	ID        uuid.UUID
	Name      string
	Slots     int32
	CpuMillis int32
	MemoryMB  int32
	Metadata  json.RawMessage
}

// UpsertWorker registers a worker by name. A worker that registers again
// (for example after a restart) keeps its ID and registered_at.
func (q *Queries) UpsertWorker(ctx context.Context, arg UpsertWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, upsertWorker,
		arg.ID,
		arg.Name,
		arg.Slots,
		arg.CpuMillis,
		arg.MemoryMB,
		arg.Metadata,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
		&i.CpuUsedPercent,
		&i.MemoryUsedMB,
	)
	return i, err
}

const workerExists = `-- name: WorkerExists :one
SELECT EXISTS (SELECT 1 FROM workers WHERE id = $1) AS found
`

func (q *Queries) WorkerExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workerExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}
