// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (id, name, slots, cpu_millis, memory_mb, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slots, cpu_millis, memory_mb, metadata, registered_at, last_heartbeat_at
`

type CreateWorkerParams struct {
	ID        uuid.UUID
	Name      string
	Slots     int32
	CpuMillis int32
	MemoryMB  int32
	Metadata  json.RawMessage
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.ID,
		arg.Name,
		arg.Slots,
		arg.CpuMillis,
		arg.MemoryMB,
		arg.Metadata,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT id, name, slots, cpu_millis, memory_mb, metadata, registered_at, last_heartbeat_at FROM workers
WHERE name = $1
`

func (q *Queries) GetWorkerByName(ctx context.Context, name string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slots,
		&i.CpuMillis,
		&i.MemoryMB,
		&i.Metadata,
		&i.RegisteredAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}
